### PR TITLE
Clean up shutdown on Debian7

### LINKED ISSUE #11: Debian 7 service stop complains "No /opt/collectd-td/sbin/collectd-td found running; none killed."
When I stop the service:

```
arielshaqed@debian7-test-2:~$ sudo /etc/init.d/collectd-td reload
[....] Stopping: collectd-td respawn collectdNo /opt/collectd-td/sbin/collectd-td found running; none killed.
[FAIL] failed to stop /opt/collectd-td/sbin/collectd-td ... failed!
[warn] Starting collectd-td: collectd-td[....] Failed to limit mem ... (warning).
. ok 
```

Unlike on Ubuntu and CentOS/Redhat, killing `simple_respawn` also kills its `collectd`. Perhaps the stop-daemon shell function sends a different signal?

### PR DESCRIPTION
**Pull request by arielshaqed**
Fixes #11 .

@yosih please review (after pull request 10 "Debian packaging: cgroups").

### CODE REVIEW

**Comment by yosih** [comment]
This looks like it contains much of pull request #10 https://github.com/GoogleCloudPlatform/collectd-netperf/pull/10/files changes from different branch into the netperf-master... Not sure how git will eat it, try to refrain from actually submitting same diffs. In the review I'm looking at new changes only.

**Comment by yosih** [comment]
LGTM

**Comment by arielshaqed** [comment]
Thanks! It contains the changes from #10 because it was staged on it. Should be better now.

**Comment by arielshaqed** [comment]
OK, rebased onto tip and everything looks nicer now. PTAL.

**Comment by yosih** [comment]
LGTM

**Comment by arielshaqed** [comment]
Thanks! Merging now...

**Pull request merged**
